apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ihos-pod
  name: ihos-pod
spec:
  containers:
  - image: ihoslav/pankoche-image:v1
    name: ihos-pod
    ports:
      - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
